// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: lumbay2.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameStatus int32

const (
	GameStatus_NONE                     GameStatus = 0
	GameStatus_WAITING_FOR_OTHER_PLAYER GameStatus = 1
	GameStatus_READY_TO_START           GameStatus = 2
	GameStatus_STARTED                  GameStatus = 3
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "NONE",
		1: "WAITING_FOR_OTHER_PLAYER",
		2: "READY_TO_START",
		3: "STARTED",
	}
	GameStatus_value = map[string]int32{
		"NONE":                     0,
		"WAITING_FOR_OTHER_PLAYER": 1,
		"READY_TO_START":           2,
		"STARTED":                  3,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lumbay2_proto_enumTypes[0].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_lumbay2_proto_enumTypes[0]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{0}
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceNumber int64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Types that are assignable to Type:
	//	*Update_Ping
	//	*Update_YouAreInGameUpdate
	//	*Update_WaitingForOtherPlayerUpdate
	//	*Update_ReadyToStartUpdate
	//	*Update_GameCodeGenerated
	Type isUpdate_Type `protobuf_oneof:"type"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (m *Update) GetType() isUpdate_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Update) GetPing() *Ping {
	if x, ok := x.GetType().(*Update_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *Update) GetYouAreInGameUpdate() *YouAreInGameUpdate {
	if x, ok := x.GetType().(*Update_YouAreInGameUpdate); ok {
		return x.YouAreInGameUpdate
	}
	return nil
}

func (x *Update) GetWaitingForOtherPlayerUpdate() *WaitingForOtherPlayerUpdate {
	if x, ok := x.GetType().(*Update_WaitingForOtherPlayerUpdate); ok {
		return x.WaitingForOtherPlayerUpdate
	}
	return nil
}

func (x *Update) GetReadyToStartUpdate() *ReadyToStartUpdate {
	if x, ok := x.GetType().(*Update_ReadyToStartUpdate); ok {
		return x.ReadyToStartUpdate
	}
	return nil
}

func (x *Update) GetGameCodeGenerated() *GameCodeGeneratedUpdate {
	if x, ok := x.GetType().(*Update_GameCodeGenerated); ok {
		return x.GameCodeGenerated
	}
	return nil
}

type isUpdate_Type interface {
	isUpdate_Type()
}

type Update_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Update_YouAreInGameUpdate struct {
	YouAreInGameUpdate *YouAreInGameUpdate `protobuf:"bytes,3,opt,name=you_are_in_game_update,json=youAreInGameUpdate,proto3,oneof"`
}

type Update_WaitingForOtherPlayerUpdate struct {
	WaitingForOtherPlayerUpdate *WaitingForOtherPlayerUpdate `protobuf:"bytes,4,opt,name=waiting_for_other_player_update,json=waitingForOtherPlayerUpdate,proto3,oneof"`
}

type Update_ReadyToStartUpdate struct {
	ReadyToStartUpdate *ReadyToStartUpdate `protobuf:"bytes,5,opt,name=ready_to_start_update,json=readyToStartUpdate,proto3,oneof"`
}

type Update_GameCodeGenerated struct {
	GameCodeGenerated *GameCodeGeneratedUpdate `protobuf:"bytes,6,opt,name=game_code_generated,json=gameCodeGenerated,proto3,oneof"`
}

func (*Update_Ping) isUpdate_Type() {}

func (*Update_YouAreInGameUpdate) isUpdate_Type() {}

func (*Update_WaitingForOtherPlayerUpdate) isUpdate_Type() {}

func (*Update_ReadyToStartUpdate) isUpdate_Type() {}

func (*Update_GameCodeGenerated) isUpdate_Type() {}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Request_AcquireClientIdRequest
	//	*Request_AcquirePublicKeyRequest
	//	*Request_CreateGameRequest
	//	*Request_GenerateGameCodeRequest
	Type isRequest_Type `protobuf_oneof:"type"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{1}
}

func (m *Request) GetType() isRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Request) GetAcquireClientIdRequest() *AcquireClientIdRequest {
	if x, ok := x.GetType().(*Request_AcquireClientIdRequest); ok {
		return x.AcquireClientIdRequest
	}
	return nil
}

func (x *Request) GetAcquirePublicKeyRequest() *AcquirePublicKeyRequest {
	if x, ok := x.GetType().(*Request_AcquirePublicKeyRequest); ok {
		return x.AcquirePublicKeyRequest
	}
	return nil
}

func (x *Request) GetCreateGameRequest() *CreateGameRequest {
	if x, ok := x.GetType().(*Request_CreateGameRequest); ok {
		return x.CreateGameRequest
	}
	return nil
}

func (x *Request) GetGenerateGameCodeRequest() *GenerateGameCodeRequest {
	if x, ok := x.GetType().(*Request_GenerateGameCodeRequest); ok {
		return x.GenerateGameCodeRequest
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_AcquireClientIdRequest struct {
	AcquireClientIdRequest *AcquireClientIdRequest `protobuf:"bytes,1,opt,name=acquire_client_id_request,json=acquireClientIdRequest,proto3,oneof"`
}

type Request_AcquirePublicKeyRequest struct {
	AcquirePublicKeyRequest *AcquirePublicKeyRequest `protobuf:"bytes,2,opt,name=acquire_public_key_request,json=acquirePublicKeyRequest,proto3,oneof"`
}

type Request_CreateGameRequest struct {
	CreateGameRequest *CreateGameRequest `protobuf:"bytes,3,opt,name=create_game_request,json=createGameRequest,proto3,oneof"`
}

type Request_GenerateGameCodeRequest struct {
	GenerateGameCodeRequest *GenerateGameCodeRequest `protobuf:"bytes,4,opt,name=generate_game_code_request,json=generateGameCodeRequest,proto3,oneof"`
}

func (*Request_AcquireClientIdRequest) isRequest_Type() {}

func (*Request_AcquirePublicKeyRequest) isRequest_Type() {}

func (*Request_CreateGameRequest) isRequest_Type() {}

func (*Request_GenerateGameCodeRequest) isRequest_Type() {}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Reply_AcquireClientIdReply
	//	*Reply_AcquirePublicKeyReply
	//	*Reply_CreateGameReply
	//	*Reply_GenerateGameCodeReply
	Type isReply_Type `protobuf_oneof:"type"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{2}
}

func (m *Reply) GetType() isReply_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Reply) GetAcquireClientIdReply() *AcquireClientIdReply {
	if x, ok := x.GetType().(*Reply_AcquireClientIdReply); ok {
		return x.AcquireClientIdReply
	}
	return nil
}

func (x *Reply) GetAcquirePublicKeyReply() *AcquirePublicKeyReply {
	if x, ok := x.GetType().(*Reply_AcquirePublicKeyReply); ok {
		return x.AcquirePublicKeyReply
	}
	return nil
}

func (x *Reply) GetCreateGameReply() *CreateGameReply {
	if x, ok := x.GetType().(*Reply_CreateGameReply); ok {
		return x.CreateGameReply
	}
	return nil
}

func (x *Reply) GetGenerateGameCodeReply() *GenerateGameCodeReply {
	if x, ok := x.GetType().(*Reply_GenerateGameCodeReply); ok {
		return x.GenerateGameCodeReply
	}
	return nil
}

type isReply_Type interface {
	isReply_Type()
}

type Reply_AcquireClientIdReply struct {
	AcquireClientIdReply *AcquireClientIdReply `protobuf:"bytes,1,opt,name=acquire_client_id_reply,json=acquireClientIdReply,proto3,oneof"`
}

type Reply_AcquirePublicKeyReply struct {
	AcquirePublicKeyReply *AcquirePublicKeyReply `protobuf:"bytes,2,opt,name=acquire_public_key_reply,json=acquirePublicKeyReply,proto3,oneof"`
}

type Reply_CreateGameReply struct {
	CreateGameReply *CreateGameReply `protobuf:"bytes,3,opt,name=create_game_reply,json=createGameReply,proto3,oneof"`
}

type Reply_GenerateGameCodeReply struct {
	GenerateGameCodeReply *GenerateGameCodeReply `protobuf:"bytes,4,opt,name=generate_game_code_reply,json=generateGameCodeReply,proto3,oneof"`
}

func (*Reply_AcquireClientIdReply) isReply_Type() {}

func (*Reply_AcquirePublicKeyReply) isReply_Type() {}

func (*Reply_CreateGameReply) isReply_Type() {}

func (*Reply_GenerateGameCodeReply) isReply_Type() {}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{3}
}

type AcquireClientIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcquireClientIdRequest) Reset() {
	*x = AcquireClientIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireClientIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireClientIdRequest) ProtoMessage() {}

func (x *AcquireClientIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireClientIdRequest.ProtoReflect.Descriptor instead.
func (*AcquireClientIdRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{4}
}

type AcquirePublicKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AcquirePublicKeyRequest) Reset() {
	*x = AcquirePublicKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquirePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquirePublicKeyRequest) ProtoMessage() {}

func (x *AcquirePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquirePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*AcquirePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{5}
}

func (x *AcquirePublicKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AcquireClientIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *AcquireClientIdReply) Reset() {
	*x = AcquireClientIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireClientIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireClientIdReply) ProtoMessage() {}

func (x *AcquireClientIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireClientIdReply.ProtoReflect.Descriptor instead.
func (*AcquireClientIdReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{6}
}

func (x *AcquireClientIdReply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AcquirePublicKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *AcquirePublicKeyReply) Reset() {
	*x = AcquirePublicKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquirePublicKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquirePublicKeyReply) ProtoMessage() {}

func (x *AcquirePublicKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquirePublicKeyReply.ProtoReflect.Descriptor instead.
func (*AcquirePublicKeyReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{7}
}

func (x *AcquirePublicKeyReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{8}
}

type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{9}
}

type GenerateGameCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateGameCodeRequest) Reset() {
	*x = GenerateGameCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateGameCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateGameCodeRequest) ProtoMessage() {}

func (x *GenerateGameCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateGameCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateGameCodeRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{10}
}

type GenerateGameCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateGameCodeReply) Reset() {
	*x = GenerateGameCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateGameCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateGameCodeReply) ProtoMessage() {}

func (x *GenerateGameCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateGameCodeReply.ProtoReflect.Descriptor instead.
func (*GenerateGameCodeReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{11}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1  string     `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2  string     `protobuf:"bytes,3,opt,name=player2,proto3" json:"player2,omitempty"`
	Status   GameStatus `protobuf:"varint,4,opt,name=status,proto3,enum=lumbay2sv.GameStatus" json:"status,omitempty"`
	GameCode string     `protobuf:"bytes,5,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{12}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *Game) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

func (x *Game) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_NONE
}

func (x *Game) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{13}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{14}
}

type YouAreInGameUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *YouAreInGameUpdate) Reset() {
	*x = YouAreInGameUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YouAreInGameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YouAreInGameUpdate) ProtoMessage() {}

func (x *YouAreInGameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YouAreInGameUpdate.ProtoReflect.Descriptor instead.
func (*YouAreInGameUpdate) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{15}
}

type WaitingForOtherPlayerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WaitingForOtherPlayerUpdate) Reset() {
	*x = WaitingForOtherPlayerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitingForOtherPlayerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingForOtherPlayerUpdate) ProtoMessage() {}

func (x *WaitingForOtherPlayerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingForOtherPlayerUpdate.ProtoReflect.Descriptor instead.
func (*WaitingForOtherPlayerUpdate) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{16}
}

type ReadyToStartUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadyToStartUpdate) Reset() {
	*x = ReadyToStartUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyToStartUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyToStartUpdate) ProtoMessage() {}

func (x *ReadyToStartUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyToStartUpdate.ProtoReflect.Descriptor instead.
func (*ReadyToStartUpdate) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{17}
}

type GameCodeGeneratedUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCode string `protobuf:"bytes,1,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
}

func (x *GameCodeGeneratedUpdate) Reset() {
	*x = GameCodeGeneratedUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCodeGeneratedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCodeGeneratedUpdate) ProtoMessage() {}

func (x *GameCodeGeneratedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCodeGeneratedUpdate.ProtoReflect.Descriptor instead.
func (*GameCodeGeneratedUpdate) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{18}
}

func (x *GameCodeGeneratedUpdate) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

var File_lumbay2_proto protoreflect.FileDescriptor

var file_lumbay2_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x22, 0xcf, 0x03, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c,
	0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x53, 0x0a, 0x16, 0x79, 0x6f, 0x75, 0x5f, 0x61, 0x72, 0x65,
	0x5f, 0x69, 0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73,
	0x76, 0x2e, 0x59, 0x6f, 0x75, 0x41, 0x72, 0x65, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x12, 0x79, 0x6f, 0x75, 0x41, 0x72, 0x65, 0x49, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x6e, 0x0a, 0x1f, 0x77, 0x61,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x1b, 0x77,
	0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x52, 0x0a, 0x15, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x75, 0x6d, 0x62,
	0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x6f, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x12, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x54, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x54,
	0x0a, 0x13, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x75,
	0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48,
	0x00, 0x52, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x87, 0x03, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5e, 0x0a, 0x19, 0x61, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x75,
	0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x16, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x61, 0x0a, 0x1a, 0x61, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c,
	0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x17, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x13, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61,
	0x79, 0x32, 0x73, 0x76, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x61, 0x0a, 0x1a, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x06,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xed, 0x02, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x58, 0x0a, 0x17, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x48, 0x00, 0x52, 0x14, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5b, 0x0a, 0x18, 0x61, 0x63,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c,
	0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00,
	0x52, 0x15, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00,
	0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x5b, 0x0a, 0x18, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x15, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x06,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x18, 0x0a, 0x16, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x17, 0x41, 0x63, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x14, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x36, 0x0a,
	0x15, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a,
	0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x95, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x12, 0x2d,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x18, 0x0a, 0x06, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x59,
	0x6f, 0x75, 0x41, 0x72, 0x65, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x36, 0x0a, 0x17, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x55,
	0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e,
	0x47, 0x5f, 0x46, 0x4f, 0x52, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x54, 0x4f,
	0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x03, 0x32, 0x7b, 0x0a, 0x0c, 0x4c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x4c,
	0x75, 0x6d, 0x62, 0x61, 0x79, 0x12, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61,
	0x79, 0x32, 0x73, 0x76, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x10, 0x2e, 0x6c, 0x75, 0x6d, 0x62,
	0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x6c, 0x75,
	0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2f,
	0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lumbay2_proto_rawDescOnce sync.Once
	file_lumbay2_proto_rawDescData = file_lumbay2_proto_rawDesc
)

func file_lumbay2_proto_rawDescGZIP() []byte {
	file_lumbay2_proto_rawDescOnce.Do(func() {
		file_lumbay2_proto_rawDescData = protoimpl.X.CompressGZIP(file_lumbay2_proto_rawDescData)
	})
	return file_lumbay2_proto_rawDescData
}

var file_lumbay2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lumbay2_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lumbay2_proto_goTypes = []interface{}{
	(GameStatus)(0),                     // 0: lumbay2sv.GameStatus
	(*Update)(nil),                      // 1: lumbay2sv.Update
	(*Request)(nil),                     // 2: lumbay2sv.Request
	(*Reply)(nil),                       // 3: lumbay2sv.Reply
	(*Empty)(nil),                       // 4: lumbay2sv.Empty
	(*AcquireClientIdRequest)(nil),      // 5: lumbay2sv.AcquireClientIdRequest
	(*AcquirePublicKeyRequest)(nil),     // 6: lumbay2sv.AcquirePublicKeyRequest
	(*AcquireClientIdReply)(nil),        // 7: lumbay2sv.AcquireClientIdReply
	(*AcquirePublicKeyReply)(nil),       // 8: lumbay2sv.AcquirePublicKeyReply
	(*CreateGameRequest)(nil),           // 9: lumbay2sv.CreateGameRequest
	(*CreateGameReply)(nil),             // 10: lumbay2sv.CreateGameReply
	(*GenerateGameCodeRequest)(nil),     // 11: lumbay2sv.GenerateGameCodeRequest
	(*GenerateGameCodeReply)(nil),       // 12: lumbay2sv.GenerateGameCodeReply
	(*Game)(nil),                        // 13: lumbay2sv.Game
	(*Client)(nil),                      // 14: lumbay2sv.Client
	(*Ping)(nil),                        // 15: lumbay2sv.Ping
	(*YouAreInGameUpdate)(nil),          // 16: lumbay2sv.YouAreInGameUpdate
	(*WaitingForOtherPlayerUpdate)(nil), // 17: lumbay2sv.WaitingForOtherPlayerUpdate
	(*ReadyToStartUpdate)(nil),          // 18: lumbay2sv.ReadyToStartUpdate
	(*GameCodeGeneratedUpdate)(nil),     // 19: lumbay2sv.GameCodeGeneratedUpdate
}
var file_lumbay2_proto_depIdxs = []int32{
	15, // 0: lumbay2sv.Update.ping:type_name -> lumbay2sv.Ping
	16, // 1: lumbay2sv.Update.you_are_in_game_update:type_name -> lumbay2sv.YouAreInGameUpdate
	17, // 2: lumbay2sv.Update.waiting_for_other_player_update:type_name -> lumbay2sv.WaitingForOtherPlayerUpdate
	18, // 3: lumbay2sv.Update.ready_to_start_update:type_name -> lumbay2sv.ReadyToStartUpdate
	19, // 4: lumbay2sv.Update.game_code_generated:type_name -> lumbay2sv.GameCodeGeneratedUpdate
	5,  // 5: lumbay2sv.Request.acquire_client_id_request:type_name -> lumbay2sv.AcquireClientIdRequest
	6,  // 6: lumbay2sv.Request.acquire_public_key_request:type_name -> lumbay2sv.AcquirePublicKeyRequest
	9,  // 7: lumbay2sv.Request.create_game_request:type_name -> lumbay2sv.CreateGameRequest
	11, // 8: lumbay2sv.Request.generate_game_code_request:type_name -> lumbay2sv.GenerateGameCodeRequest
	7,  // 9: lumbay2sv.Reply.acquire_client_id_reply:type_name -> lumbay2sv.AcquireClientIdReply
	8,  // 10: lumbay2sv.Reply.acquire_public_key_reply:type_name -> lumbay2sv.AcquirePublicKeyReply
	10, // 11: lumbay2sv.Reply.create_game_reply:type_name -> lumbay2sv.CreateGameReply
	12, // 12: lumbay2sv.Reply.generate_game_code_reply:type_name -> lumbay2sv.GenerateGameCodeReply
	0,  // 13: lumbay2sv.Game.status:type_name -> lumbay2sv.GameStatus
	2,  // 14: lumbay2sv.LumbayLumbay.SendRequest:input_type -> lumbay2sv.Request
	4,  // 15: lumbay2sv.LumbayLumbay.Subscribe:input_type -> lumbay2sv.Empty
	3,  // 16: lumbay2sv.LumbayLumbay.SendRequest:output_type -> lumbay2sv.Reply
	1,  // 17: lumbay2sv.LumbayLumbay.Subscribe:output_type -> lumbay2sv.Update
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_lumbay2_proto_init() }
func file_lumbay2_proto_init() {
	if File_lumbay2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lumbay2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireClientIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquirePublicKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireClientIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquirePublicKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateGameCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateGameCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YouAreInGameUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitingForOtherPlayerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyToStartUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCodeGeneratedUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lumbay2_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Update_Ping)(nil),
		(*Update_YouAreInGameUpdate)(nil),
		(*Update_WaitingForOtherPlayerUpdate)(nil),
		(*Update_ReadyToStartUpdate)(nil),
		(*Update_GameCodeGenerated)(nil),
	}
	file_lumbay2_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Request_AcquireClientIdRequest)(nil),
		(*Request_AcquirePublicKeyRequest)(nil),
		(*Request_CreateGameRequest)(nil),
		(*Request_GenerateGameCodeRequest)(nil),
	}
	file_lumbay2_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Reply_AcquireClientIdReply)(nil),
		(*Reply_AcquirePublicKeyReply)(nil),
		(*Reply_CreateGameReply)(nil),
		(*Reply_GenerateGameCodeReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lumbay2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lumbay2_proto_goTypes,
		DependencyIndexes: file_lumbay2_proto_depIdxs,
		EnumInfos:         file_lumbay2_proto_enumTypes,
		MessageInfos:      file_lumbay2_proto_msgTypes,
	}.Build()
	File_lumbay2_proto = out.File
	file_lumbay2_proto_rawDesc = nil
	file_lumbay2_proto_goTypes = nil
	file_lumbay2_proto_depIdxs = nil
}
