// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: lumbay2.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceNumber int64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Types that are assignable to Type:
	//	*Update_Ping
	//	*Update_YouAreInGameUpdate
	Type isUpdate_Type `protobuf_oneof:"type"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (m *Update) GetType() isUpdate_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Update) GetPing() *Ping {
	if x, ok := x.GetType().(*Update_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *Update) GetYouAreInGameUpdate() *YouAreInGameUpdate {
	if x, ok := x.GetType().(*Update_YouAreInGameUpdate); ok {
		return x.YouAreInGameUpdate
	}
	return nil
}

type isUpdate_Type interface {
	isUpdate_Type()
}

type Update_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Update_YouAreInGameUpdate struct {
	YouAreInGameUpdate *YouAreInGameUpdate `protobuf:"bytes,3,opt,name=you_are_in_game_update,json=youAreInGameUpdate,proto3,oneof"`
}

func (*Update_Ping) isUpdate_Type() {}

func (*Update_YouAreInGameUpdate) isUpdate_Type() {}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Request_AcquireClientIdRequest
	//	*Request_AcquirePublicKeyRequest
	//	*Request_CreateGameRequest
	Type isRequest_Type `protobuf_oneof:"type"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{1}
}

func (m *Request) GetType() isRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Request) GetAcquireClientIdRequest() *AcquireClientIdRequest {
	if x, ok := x.GetType().(*Request_AcquireClientIdRequest); ok {
		return x.AcquireClientIdRequest
	}
	return nil
}

func (x *Request) GetAcquirePublicKeyRequest() *AcquirePublicKeyRequest {
	if x, ok := x.GetType().(*Request_AcquirePublicKeyRequest); ok {
		return x.AcquirePublicKeyRequest
	}
	return nil
}

func (x *Request) GetCreateGameRequest() *CreateGameRequest {
	if x, ok := x.GetType().(*Request_CreateGameRequest); ok {
		return x.CreateGameRequest
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_AcquireClientIdRequest struct {
	AcquireClientIdRequest *AcquireClientIdRequest `protobuf:"bytes,1,opt,name=acquire_client_id_request,json=acquireClientIdRequest,proto3,oneof"`
}

type Request_AcquirePublicKeyRequest struct {
	AcquirePublicKeyRequest *AcquirePublicKeyRequest `protobuf:"bytes,2,opt,name=acquire_public_key_request,json=acquirePublicKeyRequest,proto3,oneof"`
}

type Request_CreateGameRequest struct {
	CreateGameRequest *CreateGameRequest `protobuf:"bytes,3,opt,name=create_game_request,json=createGameRequest,proto3,oneof"`
}

func (*Request_AcquireClientIdRequest) isRequest_Type() {}

func (*Request_AcquirePublicKeyRequest) isRequest_Type() {}

func (*Request_CreateGameRequest) isRequest_Type() {}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Reply_AcquireClientIdReply
	//	*Reply_AcquirePublicKeyReply
	//	*Reply_CreateGameReply
	Type isReply_Type `protobuf_oneof:"type"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{2}
}

func (m *Reply) GetType() isReply_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Reply) GetAcquireClientIdReply() *AcquireClientIdReply {
	if x, ok := x.GetType().(*Reply_AcquireClientIdReply); ok {
		return x.AcquireClientIdReply
	}
	return nil
}

func (x *Reply) GetAcquirePublicKeyReply() *AcquirePublicKeyReply {
	if x, ok := x.GetType().(*Reply_AcquirePublicKeyReply); ok {
		return x.AcquirePublicKeyReply
	}
	return nil
}

func (x *Reply) GetCreateGameReply() *CreateGameReply {
	if x, ok := x.GetType().(*Reply_CreateGameReply); ok {
		return x.CreateGameReply
	}
	return nil
}

type isReply_Type interface {
	isReply_Type()
}

type Reply_AcquireClientIdReply struct {
	AcquireClientIdReply *AcquireClientIdReply `protobuf:"bytes,1,opt,name=acquire_client_id_reply,json=acquireClientIdReply,proto3,oneof"`
}

type Reply_AcquirePublicKeyReply struct {
	AcquirePublicKeyReply *AcquirePublicKeyReply `protobuf:"bytes,2,opt,name=acquire_public_key_reply,json=acquirePublicKeyReply,proto3,oneof"`
}

type Reply_CreateGameReply struct {
	CreateGameReply *CreateGameReply `protobuf:"bytes,3,opt,name=create_game_reply,json=createGameReply,proto3,oneof"`
}

func (*Reply_AcquireClientIdReply) isReply_Type() {}

func (*Reply_AcquirePublicKeyReply) isReply_Type() {}

func (*Reply_CreateGameReply) isReply_Type() {}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{3}
}

type AcquireClientIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcquireClientIdRequest) Reset() {
	*x = AcquireClientIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireClientIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireClientIdRequest) ProtoMessage() {}

func (x *AcquireClientIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireClientIdRequest.ProtoReflect.Descriptor instead.
func (*AcquireClientIdRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{4}
}

type AcquirePublicKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AcquirePublicKeyRequest) Reset() {
	*x = AcquirePublicKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquirePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquirePublicKeyRequest) ProtoMessage() {}

func (x *AcquirePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquirePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*AcquirePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{5}
}

func (x *AcquirePublicKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AcquireClientIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *AcquireClientIdReply) Reset() {
	*x = AcquireClientIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireClientIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireClientIdReply) ProtoMessage() {}

func (x *AcquireClientIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireClientIdReply.ProtoReflect.Descriptor instead.
func (*AcquireClientIdReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{6}
}

func (x *AcquireClientIdReply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AcquirePublicKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *AcquirePublicKeyReply) Reset() {
	*x = AcquirePublicKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquirePublicKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquirePublicKeyReply) ProtoMessage() {}

func (x *AcquirePublicKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquirePublicKeyReply.ProtoReflect.Descriptor instead.
func (*AcquirePublicKeyReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{7}
}

func (x *AcquirePublicKeyReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{8}
}

type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{9}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1 string `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2 string `protobuf:"bytes,3,opt,name=player2,proto3" json:"player2,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{10}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *Game) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{11}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type YouAreInGameUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *YouAreInGameUpdate) Reset() {
	*x = YouAreInGameUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YouAreInGameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YouAreInGameUpdate) ProtoMessage() {}

func (x *YouAreInGameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YouAreInGameUpdate.ProtoReflect.Descriptor instead.
func (*YouAreInGameUpdate) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{12}
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{13}
}

var File_lumbay2_proto protoreflect.FileDescriptor

var file_lumbay2_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x22, 0xb5, 0x01, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c,
	0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x53, 0x0a, 0x16, 0x79, 0x6f, 0x75, 0x5f, 0x61, 0x72, 0x65,
	0x5f, 0x69, 0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73,
	0x76, 0x2e, 0x59, 0x6f, 0x75, 0x41, 0x72, 0x65, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x12, 0x79, 0x6f, 0x75, 0x41, 0x72, 0x65, 0x49, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0xa4, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5e,
	0x0a, 0x19, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x61,
	0x0a, 0x1a, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41,
	0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x4e, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x90, 0x02, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x17, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76,
	0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x14, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5b, 0x0a,
	0x18, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x48, 0x00, 0x52, 0x15, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x11, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73,
	0x76, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2d, 0x0a, 0x17, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33,
	0x0a, 0x14, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x15, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x4a, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x22,
	0x18, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x59, 0x6f, 0x75,
	0x41, 0x72, 0x65, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22,
	0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x32, 0x7b, 0x0a, 0x0c, 0x4c, 0x75, 0x6d, 0x62, 0x61,
	0x79, 0x4c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x12, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32,
	0x73, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x75, 0x6d,
	0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x10, 0x2e, 0x6c, 0x75,
	0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e,
	0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73,
	0x76, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lumbay2_proto_rawDescOnce sync.Once
	file_lumbay2_proto_rawDescData = file_lumbay2_proto_rawDesc
)

func file_lumbay2_proto_rawDescGZIP() []byte {
	file_lumbay2_proto_rawDescOnce.Do(func() {
		file_lumbay2_proto_rawDescData = protoimpl.X.CompressGZIP(file_lumbay2_proto_rawDescData)
	})
	return file_lumbay2_proto_rawDescData
}

var file_lumbay2_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_lumbay2_proto_goTypes = []interface{}{
	(*Update)(nil),                  // 0: lumbay2sv.Update
	(*Request)(nil),                 // 1: lumbay2sv.Request
	(*Reply)(nil),                   // 2: lumbay2sv.Reply
	(*Empty)(nil),                   // 3: lumbay2sv.Empty
	(*AcquireClientIdRequest)(nil),  // 4: lumbay2sv.AcquireClientIdRequest
	(*AcquirePublicKeyRequest)(nil), // 5: lumbay2sv.AcquirePublicKeyRequest
	(*AcquireClientIdReply)(nil),    // 6: lumbay2sv.AcquireClientIdReply
	(*AcquirePublicKeyReply)(nil),   // 7: lumbay2sv.AcquirePublicKeyReply
	(*CreateGameRequest)(nil),       // 8: lumbay2sv.CreateGameRequest
	(*CreateGameReply)(nil),         // 9: lumbay2sv.CreateGameReply
	(*Game)(nil),                    // 10: lumbay2sv.Game
	(*Client)(nil),                  // 11: lumbay2sv.Client
	(*YouAreInGameUpdate)(nil),      // 12: lumbay2sv.YouAreInGameUpdate
	(*Ping)(nil),                    // 13: lumbay2sv.Ping
}
var file_lumbay2_proto_depIdxs = []int32{
	13, // 0: lumbay2sv.Update.ping:type_name -> lumbay2sv.Ping
	12, // 1: lumbay2sv.Update.you_are_in_game_update:type_name -> lumbay2sv.YouAreInGameUpdate
	4,  // 2: lumbay2sv.Request.acquire_client_id_request:type_name -> lumbay2sv.AcquireClientIdRequest
	5,  // 3: lumbay2sv.Request.acquire_public_key_request:type_name -> lumbay2sv.AcquirePublicKeyRequest
	8,  // 4: lumbay2sv.Request.create_game_request:type_name -> lumbay2sv.CreateGameRequest
	6,  // 5: lumbay2sv.Reply.acquire_client_id_reply:type_name -> lumbay2sv.AcquireClientIdReply
	7,  // 6: lumbay2sv.Reply.acquire_public_key_reply:type_name -> lumbay2sv.AcquirePublicKeyReply
	9,  // 7: lumbay2sv.Reply.create_game_reply:type_name -> lumbay2sv.CreateGameReply
	1,  // 8: lumbay2sv.LumbayLumbay.SendRequest:input_type -> lumbay2sv.Request
	3,  // 9: lumbay2sv.LumbayLumbay.Subscribe:input_type -> lumbay2sv.Empty
	2,  // 10: lumbay2sv.LumbayLumbay.SendRequest:output_type -> lumbay2sv.Reply
	0,  // 11: lumbay2sv.LumbayLumbay.Subscribe:output_type -> lumbay2sv.Update
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_lumbay2_proto_init() }
func file_lumbay2_proto_init() {
	if File_lumbay2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lumbay2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireClientIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquirePublicKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireClientIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquirePublicKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YouAreInGameUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lumbay2_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Update_Ping)(nil),
		(*Update_YouAreInGameUpdate)(nil),
	}
	file_lumbay2_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Request_AcquireClientIdRequest)(nil),
		(*Request_AcquirePublicKeyRequest)(nil),
		(*Request_CreateGameRequest)(nil),
	}
	file_lumbay2_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Reply_AcquireClientIdReply)(nil),
		(*Reply_AcquirePublicKeyReply)(nil),
		(*Reply_CreateGameReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lumbay2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lumbay2_proto_goTypes,
		DependencyIndexes: file_lumbay2_proto_depIdxs,
		MessageInfos:      file_lumbay2_proto_msgTypes,
	}.Build()
	File_lumbay2_proto = out.File
	file_lumbay2_proto_rawDesc = nil
	file_lumbay2_proto_goTypes = nil
	file_lumbay2_proto_depIdxs = nil
}
