// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: lumbay2.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Request_AcquireClientIdRequest
	Type isRequest_Type `protobuf_oneof:"type"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{0}
}

func (m *Request) GetType() isRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Request) GetAcquireClientIdRequest() *AcquireClientIdRequest {
	if x, ok := x.GetType().(*Request_AcquireClientIdRequest); ok {
		return x.AcquireClientIdRequest
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_AcquireClientIdRequest struct {
	AcquireClientIdRequest *AcquireClientIdRequest `protobuf:"bytes,1,opt,name=acquire_client_id_request,json=acquireClientIdRequest,proto3,oneof"`
}

func (*Request_AcquireClientIdRequest) isRequest_Type() {}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Reply_AcquireClientIdReply
	Type isReply_Type `protobuf_oneof:"type"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{1}
}

func (m *Reply) GetType() isReply_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Reply) GetAcquireClientIdReply() *AcquireClientIdReply {
	if x, ok := x.GetType().(*Reply_AcquireClientIdReply); ok {
		return x.AcquireClientIdReply
	}
	return nil
}

type isReply_Type interface {
	isReply_Type()
}

type Reply_AcquireClientIdReply struct {
	AcquireClientIdReply *AcquireClientIdReply `protobuf:"bytes,1,opt,name=acquire_client_id_reply,json=acquireClientIdReply,proto3,oneof"`
}

func (*Reply_AcquireClientIdReply) isReply_Type() {}

type AcquireClientIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *AcquireClientIdRequest) Reset() {
	*x = AcquireClientIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireClientIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireClientIdRequest) ProtoMessage() {}

func (x *AcquireClientIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireClientIdRequest.ProtoReflect.Descriptor instead.
func (*AcquireClientIdRequest) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireClientIdRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AcquireClientIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *AcquireClientIdReply) Reset() {
	*x = AcquireClientIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lumbay2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireClientIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireClientIdReply) ProtoMessage() {}

func (x *AcquireClientIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_lumbay2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireClientIdReply.ProtoReflect.Descriptor instead.
func (*AcquireClientIdReply) Descriptor() ([]byte, []int) {
	return file_lumbay2_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireClientIdReply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_lumbay2_proto protoreflect.FileDescriptor

var file_lumbay2_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x22, 0x71, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5e, 0x0a, 0x19, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61,
	0x79, 0x32, 0x73, 0x76, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x61,
	0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x69, 0x0a,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x17, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79,
	0x32, 0x73, 0x76, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x14, 0x61, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x16, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x33, 0x0a, 0x14, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x45, 0x0a, 0x0c, 0x4c, 0x75, 0x6d, 0x62, 0x61, 0x79,
	0x4c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x12, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73,
	0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x75, 0x6d, 0x62,
	0x61, 0x79, 0x32, 0x73, 0x76, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x6c, 0x75, 0x6d, 0x62, 0x61, 0x79, 0x32, 0x73, 0x76, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lumbay2_proto_rawDescOnce sync.Once
	file_lumbay2_proto_rawDescData = file_lumbay2_proto_rawDesc
)

func file_lumbay2_proto_rawDescGZIP() []byte {
	file_lumbay2_proto_rawDescOnce.Do(func() {
		file_lumbay2_proto_rawDescData = protoimpl.X.CompressGZIP(file_lumbay2_proto_rawDescData)
	})
	return file_lumbay2_proto_rawDescData
}

var file_lumbay2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lumbay2_proto_goTypes = []interface{}{
	(*Request)(nil),                // 0: lumbay2sv.Request
	(*Reply)(nil),                  // 1: lumbay2sv.Reply
	(*AcquireClientIdRequest)(nil), // 2: lumbay2sv.AcquireClientIdRequest
	(*AcquireClientIdReply)(nil),   // 3: lumbay2sv.AcquireClientIdReply
}
var file_lumbay2_proto_depIdxs = []int32{
	2, // 0: lumbay2sv.Request.acquire_client_id_request:type_name -> lumbay2sv.AcquireClientIdRequest
	3, // 1: lumbay2sv.Reply.acquire_client_id_reply:type_name -> lumbay2sv.AcquireClientIdReply
	0, // 2: lumbay2sv.LumbayLumbay.SendRequest:input_type -> lumbay2sv.Request
	1, // 3: lumbay2sv.LumbayLumbay.SendRequest:output_type -> lumbay2sv.Reply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lumbay2_proto_init() }
func file_lumbay2_proto_init() {
	if File_lumbay2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lumbay2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireClientIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lumbay2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireClientIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lumbay2_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_AcquireClientIdRequest)(nil),
	}
	file_lumbay2_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Reply_AcquireClientIdReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lumbay2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lumbay2_proto_goTypes,
		DependencyIndexes: file_lumbay2_proto_depIdxs,
		MessageInfos:      file_lumbay2_proto_msgTypes,
	}.Build()
	File_lumbay2_proto = out.File
	file_lumbay2_proto_rawDesc = nil
	file_lumbay2_proto_goTypes = nil
	file_lumbay2_proto_depIdxs = nil
}
